/**
 * Remove instruction files generated by example:setup.
 */
import { existsSync, rmSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve("examples/test-project");
const targets = [
  "AGENTS.md",
  "CLAUDE.md",
  "GEMINI.md",
  ".github/copilot-instructions.md",
  ".github/instructions",
  ".cursor/rules",
  ".claude/rules",
  ".claude/skills",
  ".devin/rules",
  ".windsurf/rules",
  ".clinerules",
  ".gemini",
];

for (const rel of targets) {
  const abs = resolve(root, rel);
  if (!existsSync(abs)) continue;
  rmSync(abs, { recursive: true, force: true });
  console.log(`removed ${rel}`);
}

console.log("Reset done. Run: npm run example:setup");
